CREATE TABLE `zlin_ordering` (
  `ordering_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '订货订单索引id',
  `ordering_sn` bigint(20) unsigned NOT NULL COMMENT '订货订单编号',
  `pay_sn` bigint(20) unsigned NOT NULL COMMENT '订货支付单号',
  `pay_method` tinyint(1) NOT NULL DEFAULT '1' COMMENT '统一支付，0为支付到卖家，1为支付到平台，2为支付到总店',
  `pay_store_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '支付店铺ID: 0为平台，非0为店铺ID',
  `store_id` int(11) unsigned NOT NULL COMMENT '供货商店铺id',
  `store_name` varchar(50) NOT NULL COMMENT '供货商店铺名称',
  `buyer_id` int(11) unsigned NOT NULL COMMENT '买家id',
  `buyer_name` varchar(50) NOT NULL COMMENT '买家姓名',
  `buyer_email` varchar(80) DEFAULT NULL COMMENT '买家电子邮箱',
  `buyer_phone` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '买家手机',
  `add_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '订单生成时间',
  `payment_code` char(10) NOT NULL DEFAULT '' COMMENT '支付方式名称代码',
  `payment_time` int(10) unsigned DEFAULT '0' COMMENT '支付(付款)时间',
  `finnshed_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '订单完成时间',
  `goods_amount` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '商品总价格',
  `ordering_amount` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '订货订单总价格',
  `rcb_amount` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '充值卡支付金额',
  `pd_amount` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '预存款支付金额',
  `po_amount` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '积分支付金额',
  `shipping_fee` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '运费',
  `evaluation_state` tinyint(4) DEFAULT '0' COMMENT '评价状态 0未评价，1已评价，2已过期未评价',
  `evaluation_again_state` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '追加评价状态 0未评价，1已评价，2已过期未评价',
  `ordering_state` tinyint(4) NOT NULL DEFAULT '10' COMMENT '订单状态：0(已取消)10(默认):未提交;20:未付款(已提交);21:已付款;22:已付定金;30:已发货;40:已收货',
  `refund_state` tinyint(1) unsigned DEFAULT '0' COMMENT '退款状态:0是无退款,1是部分退款,2是全部退款',
  `lock_state` tinyint(1) unsigned DEFAULT '0' COMMENT '锁定状态:0是正常,大于0是锁定,默认是0',
  `delete_state` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除状态0未删除1放入回收站2彻底删除',
  `refund_amount` decimal(10,2) DEFAULT '0.00' COMMENT '退款金额',
  `delay_time` int(10) unsigned DEFAULT '0' COMMENT '延迟时间,默认为0',
	`shopping_id` tinyint(4) NOT NULL DEFAULT '1' COMMENT '订货会主题ID,来自哪次订货会',
  `ordering_from` tinyint(4) NOT NULL DEFAULT '1' COMMENT '订单来源1WEB 2mobile 3wxapp',
  `shipping_code` varchar(50) DEFAULT '' COMMENT '物流单号',
  `ordering_type` tinyint(4) DEFAULT '1' COMMENT '订单类型：1普通订单(默认),2预定订单',
  `api_pay_time` int(10) unsigned DEFAULT '0' COMMENT '在线支付动作时间,只有站内+在线组合支付时记录',
  `trade_no` varchar(50) DEFAULT NULL COMMENT '外部交易订单号',
  `saleman_id` int(11) unsigned DEFAULT NULL COMMENT '邀请人id',
  `saleman_name` varchar(50) DEFAULT NULL COMMENT '邀请人名称',
  `commis_amount` decimal(10,2) DEFAULT '0.00' COMMENT '返拥金额(积分)',
  `commis_coin` decimal(10,0) DEFAULT '0' COMMENT '返拥云币(平台货币)',
	`rebate_amount` decimal(10,2) DEFAULT '0.00' COMMENT '返利金额(积分)',
	`rebate_coin` decimal(10,0) DEFAULT '0' COMMENT '返利云币(平台货币)',
  `up_id` int(10) DEFAULT NULL COMMENT '上级店铺ID',
  `up_name` varchar(100) DEFAULT NULL COMMENT '上级店铺名称',
  PRIMARY KEY (`ordering_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='订货订单表';

CREATE TABLE `zlin_ordering_goods` (
  `rec_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '订货订单商品表索引id',
  `ordering_id` int(11) NOT NULL COMMENT '订货订单id',
  `goods_id` int(11) NOT NULL COMMENT '商品id',
  `goods_commonid` int(11) NOT NULL COMMENT '商品公共表id',
  `goods_name` varchar(50) NOT NULL COMMENT '商品名称',
  `goods_price` decimal(10,2) NOT NULL COMMENT '商品价格',
  `goods_num` smallint(5) unsigned NOT NULL DEFAULT '1' COMMENT '商品数量',
  `goods_image` varchar(100) DEFAULT NULL COMMENT '商品图片',
  `goods_pay_price` decimal(10,2) unsigned NOT NULL COMMENT '商品实际成交价',
  `store_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '供应商店铺ID',
  `buyer_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '买家ID',
  `goods_type` char(1) NOT NULL DEFAULT '1' COMMENT '1默认2团购商品3限时折扣商品4组合套装5赠品8加价购活动商品9加价购换购商品',
  `promotions_id` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT '促销活动ID（团购ID/限时折扣ID/优惠套装ID）与goods_type搭配使用',
  `commis_rate` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '佣金比例',
  `gc_id` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT '商品最底级分类ID',
  `goods_spec` varchar(255) DEFAULT NULL COMMENT '商品规格',
  `goods_contractid` varchar(100) DEFAULT NULL COMMENT '商品开启的消费者保障服务id',
  `commis_totals` decimal(10,2) DEFAULT '0.00' COMMENT '返佣金额',
  `rebate_amount` decimal(10,2) DEFAULT '0.00' COMMENT '返利金额',
  PRIMARY KEY (`rec_id`),
  KEY `ordering_id` (`ordering_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='订货订单商品表';

CREATE TABLE `zlin_ordering_common` (
  `ordering_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '订货订单索引id',
  `store_id` int(10) unsigned NOT NULL COMMENT '供应商店铺ID',
  `shipping_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '配送时间',
  `shipping_express_id` tinyint(1) NOT NULL DEFAULT '0' COMMENT '配送公司ID',
  `evaluation_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '评价时间',
  `evalseller_state` enum('0','1') NOT NULL DEFAULT '0' COMMENT '卖家是否已评价买家',
  `evalseller_time` int(10) unsigned DEFAULT NULL COMMENT '卖家评价买家的时间',
  `order_message` varchar(300) DEFAULT NULL COMMENT '订单留言',
  `voucher_price` int(11) DEFAULT NULL COMMENT '代金券面额',
  `voucher_code` varchar(32) DEFAULT NULL COMMENT '代金券编码',
  `deliver_explain` text COMMENT '发货备注',
  `daddress_id` mediumint(9) NOT NULL DEFAULT '0' COMMENT '发货地址ID',
  `reciver_name` varchar(50) NOT NULL COMMENT '收货人姓名',
  `reciver_info` varchar(500) NOT NULL COMMENT '收货人其它信息',
  `reciver_province_id` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT '收货人省级ID',
  `reciver_city_id` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT '收货人市级ID',
  `dlyo_pickup_code` varchar(4) DEFAULT NULL COMMENT '提货码',
  `promotion_total` decimal(10,2) DEFAULT '0.00' COMMENT '订单总优惠金额（代金券，满减，平台红包）',
  `discount` tinyint(4) DEFAULT '0' COMMENT '会员折扣x%',
  `invoice_info` varchar(500) DEFAULT '' COMMENT '发票信息',
  `promotion_info` varchar(500) DEFAULT '' COMMENT '促销信息备注',
  PRIMARY KEY (`ordering_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='订货订单信息扩展表';


CREATE TABLE `zlin_ordering_log` (
  `log_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ordering_id` int(11) NOT NULL COMMENT '订单id',
  `log_msg` varchar(150) DEFAULT '' COMMENT '文字描述',
  `log_time` int(10) unsigned NOT NULL COMMENT '处理时间',
  `log_role` varchar(10) NOT NULL COMMENT '操作角色',
  `log_user` varchar(30) DEFAULT '' COMMENT '操作人',
  `log_orderstate` enum('0','10','20','30','40') DEFAULT NULL COMMENT '订单状态：0(已取消)10:未付款;20:已付款;30:已发货;40:已收货;',
  PRIMARY KEY (`log_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='订货订单处理历史表';
